version: '2'
services:
  controller:
    build: ./controller
    environment:
      POSTGRES_DB: MEILI_TESTS
    depends_on:
      - db
    volumes:
      - ./controller/TestData:/testdata
    command: ./wait-for-it -t 40 db:5432 -- ./init
  db:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: MEILI_TESTS
      POSTGRES_PASSWORD: 
      PGDATA: /tmp/meili
    ports:
      - "5432:5432"
